# Generated by Django 5.1a1 on 2024-06-26 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.carrier')),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('saturday', 'Saturday'), ('sunday_holiday', 'Sunday/Holiday')], max_length=15)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.line')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.stop')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='stops',
            field=models.ManyToManyField(through='schedule.Timetable', to='schedule.stop'),
        ),
    ]
