# Generated by Django 5.1a1 on 2024-06-26 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_remove_line_stops_remove_timetable_line_line_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='previous_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_stops', to='schedule.stop'),
        ),
    ]
